sensors:
- name: kinect
  type: kinect
  source: /kinect/rgbd
  frame_id: camera_rgb_optical_frame
  visualize: 0
  voxel_size: 0.02
  max_range: 2.0
  clearing_padding_fraction: 0.05
  normal_k_search: 15
  association_modules:
  - type: PointNormal
    parameters:
        association_correspondence_distance: 0.3
        position_weight: 2.0
        normal_weight: 1.0
        render_width: 320
        render_max_range: 2.2
        render_voxel_size: 0.02
        normal_k_search: 15
        visualize: 0
  - type: PolygonHeight
    parameters:
        max_range: 2.0
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0
  segmentation_modules:
  - type: EuclideanClustering
    parameters:
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0

visualize: 1
world_name: empty

plugins:
  - name: gui_server
    lib: libed_gui_server_plugin.so
    parameters:
        robot_name: turtle
  - name: kinect_plugin
    lib: libed_kinect_plugin.so
    parameters:
        topic: /kinect/rgbd
        voxel_size: 0.02
        max_range: 2.0
        clearing_padding_fraction: 0.05
        normal_k_search: 15
        visualize: 1
        association_modules:
        - type: PointNormal
          parameters:
              association_correspondence_distance: 0.3
              position_weight: 2.0
              normal_weight: 1.0
              render_width: 320
              render_max_range: 2.2
              render_voxel_size: 0.02
              normal_k_search: 15
              visualize: 0
        - type: PolygonHeight
          parameters:
              max_range: 2.0
              tolerance: 0.035
              min_cluster_size: 20
              visualize: 0
        segmentation_modules:
        - type: EuclideanClustering
          parameters:
              tolerance: 0.035
              min_cluster_size: 20
              visualize: 0
  - name: navigation
    lib: libed_navigation_plugin.so
    parameters:
        occupancy_grid_publisher:
          frame_id: /map
          resolution: 0.05
          min_z: 0.05
          max_z: 0.80
          default_offset: 0.0
